# Generated by Django 4.2.6 on 2023-10-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
    ]
