# Generated by Django 4.2.6 on 2023-10-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(default='C:\\Users\\shin il woo\\OneDrive\\문서\\2023-4-2\\다운로드.jpg', upload_to='answer_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
    ]
