# Generated by Django 4.2.6 on 2023-10-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='useranswer_images/'),
        ),
    ]
