# Generated by Django 4.2.6 on 2023-11-09 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_useranswer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_asked',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
