# Generated by Django 4.2.6 on 2023-11-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_quiz_date_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_text_answer',
            field=models.BooleanField(default=False),
        ),
    ]
