# Generated by Django 4.2.6 on 2023-11-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_quiz_is_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_text_answer',
            field=models.BooleanField(default=False),
        ),
    ]
