# Generated by Django 4.2.6 on 2023-11-10 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_answer_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='date_answered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
